### ISSUE TITLE
0x80014 using unzip

### ISSUE THREAD

**Issue by syncingdisks** [SeunMatt/backup-mongodb-restorer#2]
Consider using node-unzip-2 maybe?

**Comment by SeunMatt** [comment]
Thanks for the suggestion @syncingdisks the whole project need a major update already and I will consider the package in the process.

Cheers

**Comment by AntilopeInteractive** [comment]
Hi, I have a question, are you fixing this problem? I need to restore a db backup and I can't for unzip error.

**Comment by neander-squirrel** [comment]
i'd be interested to have a fresh script too!
the current code exits with above mentioned error for me
